"""Deterministically generate the contained lmi P2 pmaports overlay."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import stat
import tempfile
from typing import Any

from .profile import ProfileError, SourceProfile, load_profile


PACKAGE_RELATIVE = Path("device/downstream/device-xiaomi-lmi-gui")
GENERATED_LAYOUT = "lmi-osk-layout.h"


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _sha512(payload: bytes) -> str:
    return hashlib.sha512(payload).hexdigest()


def _canonical_json(value: Any) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n").encode()


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_layout_header(profile: SourceProfile) -> bytes:
    display = profile.value["display"]
    keyboard = profile.value["keyboard"]
    lines = [
        "/* Generated by scripts.lmi_p2.generate; do not edit. */",
        "#ifndef LMI_OSK_LAYOUT_H",
        "#define LMI_OSK_LAYOUT_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct lmi_key {",
        "\tconst char *label;",
        "\tconst char *value;",
        "\tenum lmi_key_action action;",
        "\tuint16_t weight;",
        "};",
        "",
        "struct lmi_row {",
        "\tconst struct lmi_key *keys;",
        "\tsize_t key_count;",
        "\tuint32_t total_weight;",
        "};",
        "",
        "struct lmi_layer {",
        "\tconst char *name;",
        "\tconst struct lmi_row *rows;",
        "\tsize_t row_count;",
        "};",
        "",
        f"#define LMI_LOGICAL_WIDTH {display['logical_width']}",
        f"#define LMI_LOGICAL_HEIGHT {display['logical_height']}",
        f"#define LMI_OUTPUT_SCALE {display['scale']}",
        f"#define LMI_OUTPUT_CONNECTOR {_c_string(display['connector'])}",
        "#define LMI_BUFFER_WIDTH (LMI_LOGICAL_WIDTH * LMI_OUTPUT_SCALE)",
        "#define LMI_BUFFER_HEIGHT (LMI_LOGICAL_HEIGHT * LMI_OUTPUT_SCALE)",
        "#define LMI_BUFFER_STRIDE (LMI_BUFFER_WIDTH * 4)",
        f"#define LMI_MARGIN {keyboard['margin']}",
        f"#define LMI_GAP {keyboard['gap']}",
        f"#define LMI_LAYER_COUNT {len(keyboard['layers'])}",
        "#define LMI_ARRAY_LENGTH(value) (sizeof(value) / sizeof((value)[0]))",
        "",
    ]
    action_names = {
        "text": "LMI_ACTION_TEXT",
        "keysym": "LMI_ACTION_KEYSYM",
        "layer": "LMI_ACTION_LAYER",
        "modifier": "LMI_ACTION_MODIFIER",
    }
    layer_row_names: list[list[str]] = []
    for layer_index, layer in enumerate(keyboard["layers"]):
        row_names: list[str] = []
        for row_index, row in enumerate(layer["rows"]):
            row_name = f"lmi_layer_{layer_index}_row_{row_index}_keys"
            row_names.append(row_name)
            lines.append(f"static const struct lmi_key {row_name}[] = {{")
            for key in row:
                lines.append(
                    "\t{ "
                    f"{_c_string(key['label'])}, {_c_string(key['value'])}, "
                    f"{action_names[key['action']]}, {key['weight']} "
                    "},"
                )
            lines.extend(["};", ""])
        layer_row_names.append(row_names)
        rows_name = f"lmi_layer_{layer_index}_rows"
        lines.append(f"static const struct lmi_row {rows_name}[] = {{")
        for row_name, row in zip(row_names, layer["rows"], strict=True):
            lines.append(
                f"\t{{ {row_name}, LMI_ARRAY_LENGTH({row_name}), "
                f"{sum(key['weight'] for key in row)} }},"
            )
        lines.extend(["};", ""])
    lines.append("static const struct lmi_layer lmi_layers[LMI_LAYER_COUNT] = {")
    for layer_index, layer in enumerate(keyboard["layers"]):
        rows_name = f"lmi_layer_{layer_index}_rows"
        lines.append(
            f"\t{{ {_c_string(layer['name'])}, {rows_name}, "
            f"LMI_ARRAY_LENGTH({rows_name}) }},"
        )
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines).encode("ascii")


def _read_sources(profile: SourceProfile, source_root: Path) -> dict[str, bytes]:
    source_directory = source_root / "files/lmi-p2"
    result: dict[str, bytes] = {}
    for name, expected_digest in sorted(profile.value["source_files"].items()):
        path = source_directory / name
        try:
            metadata = path.lstat()
            payload = path.read_bytes()
            final = path.lstat()
        except OSError as error:
            raise ProfileError(f"could not read P2 source file {name}: {error}") from None
        if (
            not stat.S_ISREG(metadata.st_mode)
            or metadata.st_ino != final.st_ino
            or metadata.st_dev != final.st_dev
            or metadata.st_size != final.st_size
            or metadata.st_mtime_ns != final.st_mtime_ns
            or metadata.st_nlink != 1
            or metadata.st_mode & 0o022
        ):
            raise ProfileError(f"unsafe or unstable P2 source file: {name}")
        actual_digest = _sha256(payload)
        if actual_digest != expected_digest:
            raise ProfileError(
                f"P2 source digest mismatch for {name}: {actual_digest} != {expected_digest}"
            )
        result[name] = payload
    return result


def render_apkbuild(
    profile: SourceProfile, source_payloads: dict[str, bytes], layout: bytes
) -> bytes:
    package = profile.value["package"]
    pins = profile.package_pins
    dependency_lines = [
        f"{name}={record['version']}"
        for name, record in sorted(pins.items())
    ]
    build_dependencies = profile.value["build_dependencies"]
    # Alpine lifecycle scripts live beside APKBUILD and are consumed through
    # install=; unlike build inputs, they do not belong in source=/sha512sums.
    sources = {
        name: payload
        for name, payload in source_payloads.items()
        if not name.endswith((".post-install", ".post-upgrade", ".pre-deinstall"))
    }
    sources[GENERATED_LAYOUT] = layout
    lines = [
        "# Generated from config/lmi-p2/source-profile.json.",
        "# Source-only and deliberately NOT release eligible: repository/APK digests",
        "# the locked r8 baseline conflict, hardware evidence, and native terminal-focus",
        "# integration remain unresolved; see the profile release.blockers list.",
        f"pkgname={package['name']}",
        f"pkgver={package['pkgver']}",
        f"pkgrel={package['pkgrel']}",
        'pkgdesc="Bounded Weston recovery UI for Xiaomi lmi"',
        'url="https://postmarketos.org"',
        'arch="aarch64"',
        'license="MIT"',
        'options="!check"',
        'install="$pkgname.post-install $pkgname.post-upgrade $pkgname.pre-deinstall"',
        'depends="',
        *[f"\t{dependency}" for dependency in dependency_lines],
        '"',
        'makedepends="',
        *[f"\t{dependency}" for dependency in build_dependencies],
        '"',
        'source="',
        *[f"\t{name}" for name in sorted(sources)],
        '"',
        "",
        "build() {",
        '\t${CC:-cc} $CFLAGS -std=c11 -Wall -Wextra -Werror \\',
        '\t\t"$srcdir"/lmi-display-handoff.c \\',
        '\t\t"$srcdir"/lmi-child-supervisor.c $LDFLAGS \\',
        '\t\t-o "$srcdir"/lmi-display-handoff',
        '\t${CC:-cc} $CFLAGS -std=c11 -Wall -Wextra -Werror \\',
        '\t\t"$srcdir"/lmi-session-launcher.c $LDFLAGS \\',
        '\t\t-o "$srcdir"/lmi-session-launcher',
        '\t${CC:-cc} $CFLAGS -std=c11 -Wall -Wextra -Werror \\',
        '\t\t"$srcdir"/lmi-terminal-bridge.c \\',
        '\t\t"$srcdir"/lmi-child-supervisor.c $LDFLAGS \\',
        '\t\t-o "$srcdir"/lmi-terminal-bridge',
        "",
        "\twayland-scanner client-header \\",
        "\t\t/usr/share/wayland-protocols/unstable/input-method/input-method-unstable-v1.xml \\",
        '\t\t"$srcdir"/input-method-unstable-v1-client-protocol.h',
        "\twayland-scanner private-code \\",
        "\t\t/usr/share/wayland-protocols/unstable/input-method/input-method-unstable-v1.xml \\",
        '\t\t"$srcdir"/input-method-unstable-v1-protocol.c',
        '\t${CC:-cc} $CFLAGS -std=c11 -Wall -Wextra -Werror \\',
        '\t\t-I"$srcdir" $(pkg-config --cflags wayland-client pangocairo xkbcommon) \\',
        '\t\t"$srcdir"/lmi-weston-osk.c \\',
        '\t\t"$srcdir"/lmi-input-state.c \\',
        '\t\t"$srcdir"/lmi-layer-state.c \\',
        '\t\t"$srcdir"/input-method-unstable-v1-protocol.c \\',
        '\t\t$LDFLAGS $(pkg-config --libs wayland-client pangocairo xkbcommon) \\',
        '\t\t-o "$srcdir"/lmi-weston-osk',
        "}",
        "",
        "package() {",
        '\tinstall -Dm755 "$srcdir"/lmi-display-handoff \\',
        '\t\t"$pkgdir"/usr/sbin/lmi-display-handoff',
        '\tinstall -Dm755 "$srcdir"/lmi-session-launcher \\',
        '\t\t"$pkgdir"/usr/libexec/lmi-p2/lmi-session-launcher',
        '\tinstall -Dm755 "$srcdir"/lmi-weston-osk \\',
        '\t\t"$pkgdir"/usr/libexec/lmi-p2/lmi-weston-osk',
        '\tinstall -Dm755 "$srcdir"/lmi-terminal-bridge \\',
        '\t\t"$pkgdir"/usr/libexec/lmi-p2/lmi-terminal-bridge',
        '\tinstall -Dm755 "$srcdir"/lmi-account-lifecycle \\',
        '\t\t"$pkgdir"/usr/libexec/lmi-p2/lmi-account-lifecycle',
        '\tinstall -Dm755 "$srcdir"/lmi-weston-user-session \\',
        '\t\t"$pkgdir"/usr/libexec/lmi-p2/lmi-weston-user-session',
        '\tinstall -Dm755 "$srcdir"/lmi-terminal \\',
        '\t\t"$pkgdir"/usr/libexec/lmi-p2/lmi-terminal',
        '\tinstall -Dm755 "$srcdir"/lmi-editor \\',
        '\t\t"$pkgdir"/usr/libexec/lmi-p2/lmi-editor',
        '\tinstall -Dm755 "$srcdir"/lmi-display.initd \\',
        '\t\t"$pkgdir"/etc/init.d/lmi-display',
        '\tinstall -Dm644 "$srcdir"/weston.ini \\',
        '\t\t"$pkgdir"/etc/lmi-p2/weston.ini',
        '\tinstall -d -m755 "$pkgdir"/etc/runlevels/default',
        '\tln -s /etc/init.d/seatd "$pkgdir"/etc/runlevels/default/seatd',
        '\tln -s /etc/init.d/lmi-display "$pkgdir"/etc/runlevels/default/lmi-display',
        "}",
        "",
        'sha512sums="',
        *[f"{_sha512(payload)}  {name}" for name, payload in sorted(sources.items())],
        '"',
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def generate_overlay_from_profile(
    profile: SourceProfile, output: Path, *, source_root: Path | None = None
) -> Path:
    """Generate solely from one retained, already-validated profile snapshot."""

    if source_root is None:
        source_root = Path(__file__).resolve().parents[2]
    source_root = source_root.resolve(strict=True)
    output = output.absolute()
    if output.exists() or output.is_symlink():
        raise ProfileError(f"refusing to overwrite existing output: {output}")
    parent = output.parent
    try:
        parent_metadata = parent.lstat()
    except OSError as error:
        raise ProfileError(f"output parent is unavailable: {error}") from None
    if not stat.S_ISDIR(parent_metadata.st_mode) or stat.S_ISLNK(parent_metadata.st_mode):
        raise ProfileError("output parent must be one real directory")

    source_payloads = _read_sources(profile, source_root)
    layout = render_layout_header(profile)
    apkbuild = render_apkbuild(profile, source_payloads, layout)
    temporary = Path(tempfile.mkdtemp(prefix=".lmi-p2-overlay-", dir=parent))
    try:
        temporary.chmod(0o755)
        package_directory = temporary / PACKAGE_RELATIVE
        package_directory.mkdir(parents=True, mode=0o755)
        current = temporary
        for component in PACKAGE_RELATIVE.parts:
            current /= component
            current.chmod(0o755)
        outputs = {**source_payloads, GENERATED_LAYOUT: layout, "APKBUILD": apkbuild}
        for name, payload in sorted(outputs.items()):
            destination = package_directory / name
            destination.write_bytes(payload)
            destination.chmod(0o644)
        manifest = {
            "files": {
                f"{PACKAGE_RELATIVE.as_posix()}/{name}": {
                    "sha256": _sha256(payload),
                    "size": len(payload),
                }
                for name, payload in sorted(outputs.items())
            },
            "profile_sha256": profile.sha256,
            "release_eligible": False,
            "schema": "lmi-p2-generated-overlay/v1",
        }
        (temporary / ".lmi-p2-overlay.json").write_bytes(_canonical_json(manifest))
        (temporary / ".lmi-p2-overlay.json").chmod(0o644)
        os.rename(temporary, output)
    except BaseException:
        shutil.rmtree(temporary, ignore_errors=True)
        raise
    return output / PACKAGE_RELATIVE


def generate_overlay(
    profile_path: Path, output: Path, *, source_root: Path | None = None
) -> Path:
    """Validate one profile snapshot, then generate without rereading it."""

    return generate_overlay_from_profile(
        load_profile(profile_path), output, source_root=source_root
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--require-release-ready",
        action="store_true",
        help="fail unless all artifact/index pins and the kernel blocker are resolved",
    )
    arguments = parser.parse_args(argv)
    try:
        profile = load_profile(arguments.profile)
        if arguments.require_release_ready:
            profile.require_release_ready()
        package = generate_overlay_from_profile(profile, arguments.output)
    except ProfileError as error:
        parser.error(str(error))
    print(package)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
