#!/usr/bin/env bash
set -euo pipefail

copydown_dir=${OUT_DIR:-/tmp/lmi-copydown-r6-bootmem-20260624}
export_dir=${PMOS_EXPORT_DIR:-/tmp/postmarketOS-export}
bundle_dir=${LMI_RELEASE_BUNDLE_DIR:-/tmp/lmi-release-r6-bootmem-20260624}
release_tag=${LMI_RELEASE_TAG:-r6-bootmem}

boot_img=$copydown_dir/boot-linux-copydown-lmi.img
manifest=$copydown_dir/boot-linux-copydown-lmi.manifest
rootfs_img=$export_dir/xiaomi-lmi.img
direct_boot_img=$export_dir/boot.img
vmlinuz=$export_dir/vmlinuz
runtime_dtb=$export_dir/dtbs/sm8250-xiaomi-lmi.dtb
initramfs=$export_dir/initramfs

for path in "$boot_img" "$manifest" "$rootfs_img" "$direct_boot_img" "$vmlinuz" "$runtime_dtb" "$initramfs"; do
	[ -f "$path" ] || {
		echo "missing file: $path" >&2
		exit 2
	}
done

mkdir -p "$bundle_dir"
cp -f "$boot_img" "$bundle_dir/boot-linux-copydown-lmi-$release_tag.img"
cp -f "$manifest" "$bundle_dir/boot-linux-copydown-lmi-$release_tag.manifest"
cp -f "$rootfs_img" "$bundle_dir/xiaomi-lmi-$release_tag.img"
cp -f "$direct_boot_img" "$bundle_dir/pmbootstrap-direct-boot-$release_tag.img"
cp -f "$vmlinuz" "$bundle_dir/vmlinuz-$release_tag"
cp -f "$runtime_dtb" "$bundle_dir/sm8250-xiaomi-lmi-$release_tag.dtb"
cp -f "$initramfs" "$bundle_dir/initramfs-$release_tag"

(
	cd "$bundle_dir"
	sha256sum \
		"boot-linux-copydown-lmi-$release_tag.img" \
		"boot-linux-copydown-lmi-$release_tag.manifest" \
		"xiaomi-lmi-$release_tag.img" \
		"pmbootstrap-direct-boot-$release_tag.img" \
		"vmlinuz-$release_tag" \
		"sm8250-xiaomi-lmi-$release_tag.dtb" \
		"initramfs-$release_tag" > SHA256SUMS
)

cat > "$bundle_dir/README.txt" <<'EOF'
Xiaomi lmi host-side bundle

Contents:
- boot-linux-copydown-lmi-<release-tag>.img
  Candidate boot image. This is the copydown/bootshim image, not the direct
  pmbootstrap boot.img.
- boot-linux-copydown-lmi-<release-tag>.manifest
  Copydown manifest generated by the historical lmi boot packaging flow.
- xiaomi-lmi-<release-tag>.img
  postmarketOS rootfs sparse image. Flashing this to userdata is destructive.
- pmbootstrap-direct-boot-<release-tag>.img
  Direct pmbootstrap boot image kept for comparison only.
- vmlinuz-<release-tag>
- sm8250-xiaomi-lmi-<release-tag>.dtb
- initramfs-<release-tag>
- SHA256SUMS

Safety boundary:
- Do not flash from bootloader fastboot as a default path.
- For persistent boot image testing, use recovery fastbootd only after
  `fastboot getvar is-userspace` returns `yes`.
- Do not flash boot/rootfs without fresh exact approval for the exact command.
- Do not touch super, dtbo, vbmeta, persist, modem/EFS/calibration partitions,
  vendor_boot, init_boot, or bootloader relock paths.

Expected preflight:
1. scripts/46_verify_lmi_copydown_boot.sh with OUT_DIR set to the copydown dir.
2. scripts/48_preflight_lmi_fastbootd.sh with LMI_COPYDOWN_BOOT_IMG and
   LMI_COPYDOWN_MANIFEST pointing to this bundle.
3. Verify a known-good rollback boot image and ROM/recovery path before any write.
EOF

printf 'release_tag=%s\n' "$release_tag" > "$bundle_dir/RELEASE_TAG"

echo "release bundle: $bundle_dir"
echo "sha256sums: $bundle_dir/SHA256SUMS"
