#!/usr/bin/env bash
set -euo pipefail

# Shared release env defaults (OUT_DIR/PMOS_EXPORT_DIR/
# LMI_RELEASE_BUNDLE_DIR/LMI_RELEASE_TAG overrides win).
. "$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/lib/mainline_r6_env.sh"

copydown_dir=$lmi_default_out_dir
export_dir=$lmi_default_export_dir
bundle_dir=$lmi_default_bundle_dir
release_tag=$lmi_default_release_tag

boot_img=$copydown_dir/boot-linux-copydown-lmi.img
manifest=$copydown_dir/boot-linux-copydown-lmi.manifest
rootfs_img=$export_dir/xiaomi-lmi.img
direct_boot_img=$export_dir/boot.img
vmlinuz=$export_dir/vmlinuz
runtime_dtb=$export_dir/dtbs/sm8250-xiaomi-lmi.dtb
initramfs=$export_dir/initramfs

for path in "$boot_img" "$manifest" "$rootfs_img" "$direct_boot_img" "$vmlinuz" "$runtime_dtb" "$initramfs"; do
	[ -f "$path" ] || {
		echo "missing file: $path" >&2
		exit 2
	}
done

mkdir -p "$bundle_dir"
cp -f "$boot_img" "$bundle_dir/boot-linux-copydown-lmi-$release_tag.img"
cp -f "$manifest" "$bundle_dir/boot-linux-copydown-lmi-$release_tag.manifest"
cp -f "$rootfs_img" "$bundle_dir/xiaomi-lmi-$release_tag.img"
cp -f "$direct_boot_img" "$bundle_dir/pmbootstrap-direct-boot-$release_tag.img"
cp -f "$vmlinuz" "$bundle_dir/vmlinuz-$release_tag"
cp -f "$runtime_dtb" "$bundle_dir/sm8250-xiaomi-lmi-$release_tag.dtb"
cp -f "$initramfs" "$bundle_dir/initramfs-$release_tag"

(
	cd "$bundle_dir"
	sha256sum \
		"boot-linux-copydown-lmi-$release_tag.img" \
		"boot-linux-copydown-lmi-$release_tag.manifest" \
		"xiaomi-lmi-$release_tag.img" \
		"pmbootstrap-direct-boot-$release_tag.img" \
		"vmlinuz-$release_tag" \
		"sm8250-xiaomi-lmi-$release_tag.dtb" \
		"initramfs-$release_tag" > SHA256SUMS
)

cat > "$bundle_dir/README.txt" <<'EOF'
Xiaomi lmi host-side bundle

Contents:
- boot-linux-copydown-lmi-<release-tag>.img
  Candidate boot image. This is the copydown/bootshim image, not the direct
  pmbootstrap boot.img.
- boot-linux-copydown-lmi-<release-tag>.manifest
  Copydown manifest generated by the historical lmi boot packaging flow.
- xiaomi-lmi-<release-tag>.img
  postmarketOS rootfs sparse image. Flashing this to userdata is destructive.
- pmbootstrap-direct-boot-<release-tag>.img
  Direct pmbootstrap boot image kept for comparison only.
- vmlinuz-<release-tag>
- sm8250-xiaomi-lmi-<release-tag>.dtb
- initramfs-<release-tag>
- SHA256SUMS

Safety boundary:
- This is a host-side artifact bundle, not an authorization or execution
  procedure.
- Persistent testing requires a reviewed profile with a distinct-hash rollback
  artifact, an owner `bringup_loop.py authorize-profile` declaration, a fresh
  experiment, preflight, and one-shot claim.
- The governance engine does not execute device commands. Use only an executor
  adapter that consumes the claimed exact command and enforces the live device
  gates; no generic adapter is wired for this historical bundle.
- Do not touch super, dtbo, vbmeta, persist, modem/EFS/calibration partitions,
  vendor_boot, init_boot, or bootloader relock paths.

Expected host-side checks:
1. scripts/46_verify_lmi_copydown_boot.sh with OUT_DIR set to the copydown dir.
2. Verify SHA256SUMS from inside this bundle.
3. Treat the bundle as historical until a fresh reviewed profile and executor
   adapter exist.
EOF

printf 'release_tag=%s\n' "$release_tag" > "$bundle_dir/RELEASE_TAG"

echo "release bundle: $bundle_dir"
echo "sha256sums: $bundle_dir/SHA256SUMS"
